//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketBooking.Admin
{
    public partial class ManageShowtimes
    {
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.GridView gvShowtimes;
        protected global::System.Web.UI.WebControls.Label lblNoData;
        protected global::System.Web.UI.WebControls.DropDownList ddlMovies;
        protected global::System.Web.UI.WebControls.TextBox txtTheater;
        protected global::System.Web.UI.WebControls.TextBox txtStartTime;
        protected global::System.Web.UI.WebControls.TextBox txtPrice;
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
