//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketBooking.Admin
{
    public partial class ManageBookings
    {
        protected global::System.Web.UI.WebControls.GridView gvBookings;
        protected global::System.Web.UI.WebControls.Label lblNoData;
        protected global::System.Web.UI.WebControls.Label lblTotalRevenue;
    }
}
